name = "aoe2backend-data-proxy-worker"
main = "src/index.ts"
compatibility_date = "2022-10-20"

usage_model = "bundled"

# needed?
#node_compat = true

kv_namespaces = [
    { binding = "AOE2COMPANION", id = "5328970bb8eb4207ae4770f5f9ad31a9", preview_id = "5328970bb8eb4207ae4770f5f9ad31a9" }
]

[vars]
#DATABASE_URL = "prisma://aws-us-east-1.prisma-data.com/?api_key=•••••••••••••••••"

# The necessary secrets are:
# - DATABASE_URL

# Run `echo <VALUE> | wrangler secret put DATABASE_URL` for it


